name: Server Integration Test
on:
  push:
    branches: 
      - 'main'
      - 'cp2-server*'
      - 'rust-integration-test'
  pull_request:
    branches: 
      - 'main'
env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    defaults:
      run:
        shell: bash
        working-directory: ./server
    runs-on: self-hosted
    continue-on-error: false

    steps:
    - uses: actions/checkout@v3
    - name: Install Toolchain
      run: rustup update stable && rustup default stable && rustup component add rustfmt
    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov
    - name: Run mock S3 server
      run: docker run -p 6333:80 -v ${{ github.workspace }}/server/tests/test_s3_files:/usr/share/nginx/html -d nginx
    - name: setup-redis
      uses: shogo82148/actions-setup-redis@v1
      with:
        auto-start: false
    - name: start redis nodes
      run: ${{ github.workspace }}/server/tests/test_setup_redis.sh
    - name: Generate code coverage
      run: cargo llvm-cov --all-features --workspace --codecov --output-path lcov.info
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: lcov.info
        retention-days: 3
    - name: Upload to codecov
      uses: codecov/codecov-action@v3
      with:
        token: be8874e2-10d6-434f-9d52-db6094de31d6
        files: lcov.info
        name: codecov-umbrella # optional
        fail_ci_if_error: true
        verbose: true